name: jk_main_menu
version: '${project.version}'
main: jiekie.mainmenu.MainMenuPlugin
api-version: '1.20'
authors: [Jiekie]
description: 메인 메뉴 플러그인
commands:
  메인메뉴:
    description: 메인 메뉴 명령어
    usage: /메인메뉴